// ─────────────────────────────────────────
// SCRIPT GENERATOR
// ─────────────────────────────────────────

function generateScript() {
  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# Statusline — generated by statusline-editor.html v2');
  lines.push('');
  lines.push('JSON_INPUT=$(cat)');
  lines.push('');
  lines.push('model=$(echo "$JSON_INPUT" | jq -r \'.model.display_name // "Claude"\' | sed \'s/^Claude //\')');
  lines.push('input=$(echo "$JSON_INPUT" | jq -r \'.context_window.total_input_tokens // 0\')');
  lines.push('output=$(echo "$JSON_INPUT" | jq -r \'.context_window.total_output_tokens // 0\')');
  lines.push('percent=$(echo "$JSON_INPUT" | jq -r \'.context_window.used_percentage // 0\')');
  lines.push('cwd=$(echo "$JSON_INPUT" | jq -r \'.cwd // (.workspace.current_dir // "")\')');
  lines.push('');
  lines.push('RESET="\\033[0m"');
  if (state.globalSepEnabled && state.globalSep) {
    lines.push(`SEP_COLOR="\\033[38;5;${state.globalSepColor}m"`);
  }

  state.blocks.forEach(block => {
    if (!block.enabled) return;
    switch (block.id) {
      case 'model':
        lines.push(`MODEL_COLOR="\\033[38;5;${block.color}m"`);
        break;
      case 'context':
        lines.push(`CTX_LOW="\\033[38;5;${block.thresholds[0].color}m"`);
        lines.push(`CTX_MID="\\033[38;5;${block.thresholds[1].color}m"`);
        lines.push(`CTX_HIGH="\\033[38;5;${block.thresholds[2].color}m"`);
        break;
      case 'rate5h':
        lines.push(`RATE5H_COLOR="\\033[38;5;${block.color}m"`);
        break;
      case 'rateWeek':
        lines.push(`RATEWEEK_COLOR="\\033[38;5;${block.color}m"`);
        break;
      case 'tokens':
        lines.push(`TOKEN_COLOR="\\033[38;5;${block.color}m"`);
        break;
      case 'directory':
        lines.push(`DIR_COLOR="\\033[38;5;${block.color}m"`);
        if (block.showGit) {
          lines.push(`GIT_COLOR="\\033[38;5;${block.colorBranch}m"`);
          lines.push(`GIT_CLEAN="\\033[38;5;${block.colorClean}m"`);
          lines.push(`GIT_DIRTY="\\033[38;5;${block.colorDirty}m"`);
        }
        break;
    }
  });

  lines.push('');

  // Bar function if rate blocks enabled
  const hasRate = state.blocks.some(b => (b.id === 'rate5h' || b.id === 'rateWeek') && b.enabled);
  if (hasRate) {
    const rateBlock = state.blocks.find(b => (b.id === 'rate5h' || b.id === 'rateWeek') && b.enabled);
    const style = rateBlock ? rateBlock.style : 'classic';
    if (style === 'emoji') {
      lines.push('get_rate_bar() {');
      lines.push('  local p=$1 len=${2:-8} bar=""');
      lines.push('  local filled=$(( p * len / 100 ))');
      lines.push('  local empty=$(( len - filled ))');
      lines.push('  local fc; if (( p < 50 )); then fc="🟢"; elif (( p < 80 )); then fc="🟡"; else fc="🔴"; fi');
      lines.push('  for ((i=0;i<filled;i++)); do bar+="$fc"; done');
      lines.push('  for ((i=0;i<empty;i++)); do bar+="⚪"; done');
      lines.push('  echo "$bar"');
      lines.push('}');
    } else if (style === 'gradient') {
      lines.push('get_rate_bar() {');
      lines.push('  local p=$1 len=${2:-8} bar=""');
      lines.push('  local filled=$(( p * len / 100 ))');
      lines.push('  local empty=$(( len - filled ))');
      lines.push('  for ((i=0;i<filled;i++)); do');
      lines.push('    local ratio=$(( i * 10 / len ))');
      lines.push('    if (( ratio < 4 )); then bar+="█"; elif (( ratio < 7 )); then bar+="▓"; else bar+="▒"; fi');
      lines.push('  done');
      lines.push('  for ((i=0;i<empty;i++)); do bar+="░"; done');
      lines.push('  echo "$bar"');
      lines.push('}');
    } else {
      const cfg = BAR_STYLES[style] || BAR_STYLES.classic;
      lines.push(`RATE_FILLED="${cfg.filled}"`);
      lines.push(`RATE_EMPTY="${cfg.empty}"`);
      lines.push('get_rate_bar() {');
      lines.push('  local p=$1 len=${2:-8} bar=""');
      lines.push('  local filled=$(( p * len / 100 ))');
      lines.push('  local empty=$(( len - filled ))');
      lines.push('  for ((i=0;i<filled;i++)); do bar+="${RATE_FILLED}"; done');
      lines.push('  for ((i=0;i<empty;i++)); do bar+="${RATE_EMPTY}"; done');
      lines.push('  echo "$bar"');
      lines.push('}');
    }
    lines.push('');
  }

  // Directory function
  const dirBlock = state.blocks.find(b => b.id === 'directory' && b.enabled);
  lines.push('get_directory() {');
  if (dirBlock && dirBlock.depth === 0) {
    lines.push('  echo "$1"');
  } else if (dirBlock && dirBlock.depth === 1) {
    lines.push('  echo "$(basename "$1")"');
  } else {
    lines.push('  local parent=$(basename "$(dirname "$1")")');
    lines.push('  local current=$(basename "$1")');
    lines.push('  if [[ "$parent" == "/" || -z "$parent" ]]; then echo "~/${current}"; else echo "~/${parent}/${current}"; fi');
  }
  lines.push('}');
  lines.push('');

  // Git helpers
  const gitBlock = state.blocks.find(b => b.id === 'git' && b.enabled);
  if (gitBlock) {
    lines.push('get_git_branch() { git -C "$1" rev-parse --abbrev-ref HEAD 2>/dev/null; }');
    lines.push('get_git_status() {');
    lines.push('  git -C "$1" diff --quiet 2>/dev/null && git -C "$1" diff --cached --quiet 2>/dev/null && echo clean || echo dirty');
    lines.push('}');
    lines.push('');
  }

  // Token format
  const tokBlock = state.blocks.find(b => b.id === 'tokens' && b.enabled);
  if (tokBlock) {
    if (tokBlock.format === '1000') {
      lines.push('format_tokens() { echo "$1"; }');
    } else if (tokBlock.format === '1.2k') {
      lines.push('format_tokens() { printf "%.1fk" "$(echo "scale=1; $1/1000" | bc)"; }');
    } else {
      lines.push('format_tokens() { echo $(($1 / 1000)); }');
    }
    lines.push('');
  }

  // Context color
  const ctxBlock = state.blocks.find(b => b.id === 'context' && b.enabled);
  if (ctxBlock) {
    lines.push('get_ctx_color() {');
    lines.push('  local p=$1');
    lines.push(`  if (( p < ${ctxBlock.thresholds[1].max} )); then echo -e "$CTX_LOW"`);
    lines.push(`  elif (( p < ${ctxBlock.thresholds[2].max} )); then echo -e "$CTX_MID"`);
    lines.push('  else echo -e "$CTX_HIGH"');
    lines.push('  fi');
    lines.push('}');
    lines.push('');
  }

  // Compute values
  lines.push('# ── Compute values ──');
  lines.push('directory=$(get_directory "$cwd")');
  if (tokBlock) {
    lines.push('input_k=$(format_tokens "$input")');
    lines.push('output_k=$(format_tokens "$output")');
  }
  if (ctxBlock) {
    lines.push('ctx_color=$(get_ctx_color "$percent")');
  }
  lines.push('');

  // Print statusline
  lines.push('# ── Print statusline ──');
  let firstBlock = true;
  for (const block of state.blocks) {
    if (!block.enabled) continue;
    if (!firstBlock && state.globalSepEnabled && state.globalSep) {
      lines.push(`printf "\${SEP_COLOR}${state.globalSep}\${RESET} "`);
    }
    firstBlock = false;
    switch (block.id) {
      case 'model':
        lines.push(`printf "\${MODEL_COLOR}[%s]\${RESET} " "$model"`);
        break;
      case 'context':
        if (block.showContextTokens) {
          lines.push(`CTX_MAX=200000  # Max context tokens for current model`);
          lines.push(`used_tokens=$((CTX_MAX * percent / 100 / 1000))`);
          lines.push(`max_tokens=$((CTX_MAX / 1000))`);
          lines.push(`printf "\${ctx_color} %s%%\${RESET} \${CTX_TOKENS_COLOR}(%sK/%sK)\${RESET} " "$percent" "$used_tokens" "$max_tokens"`);
        } else {
          lines.push(`printf "\${ctx_color} %s%%\${RESET} " "$percent"`);
        }
        break;
      case 'rate5h':
        lines.push('# rate5h: requires rate limit data in JSON input (not available in Claude Code yet)');
        lines.push('# rate5h_pct=$(echo "$JSON_INPUT" | jq -r \'.rate_limits.five_hour_pct // 0\')');
        if (block.showReset) {
          lines.push('# rate5h_reset=$(echo "$JSON_INPUT" | jq -r \'.rate_limits.five_hour_reset // ""\')');
          lines.push('# printf "${RATE5H_COLOR}%s %s%%" "$(get_rate_bar $rate5h_pct)" "$rate5h_pct"');
          lines.push('# [[ -n "$rate5h_reset" ]] && printf " \\033[38;5;238m%s${RESET}" "$rate5h_reset"');
          lines.push('# printf " ${RESET}"');
        } else {
          lines.push('# printf "${RATE5H_COLOR}%s %s%%${RESET} " "$(get_rate_bar $rate5h_pct)" "$rate5h_pct"');
        }
        break;
      case 'rateWeek':
        lines.push('# rateWeek: requires rate limit data in JSON input (not available in Claude Code yet)');
        lines.push('# rate_week_pct=$(echo "$JSON_INPUT" | jq -r \'.rate_limits.week_pct // 0\')');
        if (block.showReset) {
          lines.push('# rate_week_reset=$(echo "$JSON_INPUT" | jq -r \'.rate_limits.week_reset // ""\')');
          lines.push('# printf "${RATEWEEK_COLOR}%s %s%%" "$(get_rate_bar $rate_week_pct)" "$rate_week_pct"');
          lines.push('# [[ -n "$rate_week_reset" ]] && printf " \\033[38;5;238m%s${RESET}" "$rate_week_reset"');
          lines.push('# printf " ${RESET}"');
        } else {
          lines.push('# printf "${RATEWEEK_COLOR}W%s %%${RESET} " "$rate_week_pct"');
        }
        break;
      case 'tokens':
        lines.push(`printf "\${TOKEN_COLOR}↑%s ↓%s\${RESET} " "$input_k" "$output_k"`);
        break;
      case 'directory':
        lines.push(`printf "\${DIR_COLOR}%s\${RESET}" "$directory"`);
        if (block.showGit) {
          lines.push('if [[ -n "$cwd" ]]; then');
          lines.push('  git_branch=$(get_git_branch "$cwd")');
          lines.push('  if [[ -n "$git_branch" ]]; then');
          lines.push('    git_status=$(get_git_status "$cwd")');
          lines.push('    printf " \${GIT_COLOR}(%s)\${RESET}" "$git_branch"');

          lines.push('  fi');
          lines.push('fi');
        }
        break;
    }
    lines.push(`printf " "`);
  }

  lines.push('');
  return lines.join('\n');
}
