// ─────────────────────────────────────────
// SCRIPT GENERATOR
// ─────────────────────────────────────────

function generateScript() {
  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# Statusline — generated by statusline-editor.html v2');
  lines.push('');
  lines.push('JSON_INPUT=$(cat)');
  lines.push('');
  lines.push('model=$(echo "$JSON_INPUT" | jq -r \'.model.display_name // "Claude"\' | sed \'s/^Claude //\')');
  lines.push('input=$(echo "$JSON_INPUT" | jq -r \'.context_window.total_input_tokens // 0\')');
  lines.push('output=$(echo "$JSON_INPUT" | jq -r \'.context_window.total_output_tokens // 0\')');
  lines.push('percent=$(echo "$JSON_INPUT" | jq -r \'.context_window.used_percentage // 0\' | cut -d. -f1)');
  lines.push('cwd=$(echo "$JSON_INPUT" | jq -r \'.cwd // (.workspace.current_dir // "")\')');
  lines.push('');

  const hasRate = state.blocks.some(b => (b.id === 'rate5h' || b.id === 'rateWeek') && b.enabled);
  if (hasRate) {
    lines.push('# ── Usage Limits (Anthropic API, cached 2 min) ──');
    lines.push('CACHE_FILE="$HOME/.claude/.usage-cache.json"');
    lines.push('');
    lines.push('fetch_usage() {');
    lines.push('    local token');
    lines.push('    token=$(security find-generic-password -s "Claude Code-credentials" -w 2>/dev/null \\');
    lines.push('        | python3 -c "import sys,json; d=json.load(sys.stdin); print(d[\'claudeAiOauth\'][\'accessToken\'])" 2>/dev/null)');
    lines.push('    [ -z "$token" ] && return');
    lines.push('    curl -sf --max-time 5 "https://api.anthropic.com/api/oauth/usage" \\');
    lines.push('        -H "Authorization: Bearer $token" \\');
    lines.push('        -H "anthropic-beta: oauth-2025-04-20" \\');
    lines.push('        -H "Accept: application/json" 2>/dev/null');
    lines.push('}');
    lines.push('');
    lines.push('get_usage() {');
    lines.push('    local now cache_time=0');
    lines.push('    now=$(date +%s)');
    lines.push('    [ -f "$CACHE_FILE" ] && cache_time=$(stat -f %m "$CACHE_FILE" 2>/dev/null || stat -c %Y "$CACHE_FILE" 2>/dev/null || echo 0)');
    lines.push('    if [ $((now - cache_time)) -gt 120 ]; then');
    lines.push('        local data');
    lines.push('        data=$(fetch_usage)');
    lines.push('        if [ -n "$data" ] && echo "$data" | jq -e .five_hour >/dev/null 2>&1; then');
    lines.push('            umask 077 && echo "$data" > "$CACHE_FILE"');
    lines.push('        fi');
    lines.push('    fi');
    lines.push('    [ -f "$CACHE_FILE" ] && cat "$CACHE_FILE"');
    lines.push('}');
    lines.push('');
    lines.push('usage_data=$(get_usage)');
    lines.push('five_h_left="" week_left="" time_left="" week_reset_str=""');
    lines.push('');
    lines.push('if [ -n "$usage_data" ]; then');
    lines.push('    five_h_used=$(echo "$usage_data" | jq -r ".five_hour.utilization // 0")');
    lines.push('    week_used=$(echo "$usage_data"  | jq -r ".seven_day.utilization  // 0")');
    lines.push('    five_h_reset_at=$(echo "$usage_data" | jq -r ".five_hour.resets_at // \\"\\"")');
    lines.push('    week_reset_at=$(echo "$usage_data"   | jq -r ".seven_day.resets_at  // \\"\\"")');
    lines.push('');
    lines.push('    five_h_left=$(python3 -c "import sys; print(int(100 - float(sys.argv[1])))" "$five_h_used" 2>/dev/null || echo "?")');
    lines.push('    week_left=$(python3   -c "import sys; print(int(100 - float(sys.argv[1])))" "$week_used"   2>/dev/null || echo "?")');
    lines.push('');
    lines.push("    [ -n \"$five_h_reset_at\" ] && time_left=$(python3 -c \"");
    lines.push('import sys');
    lines.push('from datetime import datetime, timezone');
    lines.push("reset = datetime.fromisoformat(sys.argv[1].replace('Z','+00:00'))");
    lines.push('s = int((reset - datetime.now(timezone.utc)).total_seconds())');
    lines.push('h, m = s // 3600, (s % 3600) // 60');
    lines.push("print(str(h) + 'h' + str(m) + 'm' if h > 0 else str(m) + 'm')");
    lines.push("\" \"$five_h_reset_at\" 2>/dev/null)");
    lines.push('');
    lines.push("    [ -n \"$week_reset_at\" ] && week_reset_str=$(python3 -c \"");
    lines.push('import sys');
    lines.push('from datetime import datetime, timezone');
    lines.push("reset = datetime.fromisoformat(sys.argv[1].replace('Z','+00:00'))");
    lines.push('s = int((reset - datetime.now(timezone.utc)).total_seconds())');
    lines.push('d, h = s // 86400, (s % 86400) // 3600');
    lines.push("print(str(d) + 'd' + str(h) + 'h' if d > 0 else str(h) + 'h')");
    lines.push("\" \"$week_reset_at\" 2>/dev/null)");
    lines.push('fi');
    lines.push('');
  }

  lines.push('RESET="\\033[0m"');
  if (state.globalSepEnabled && state.globalSep) {
    lines.push(`SEP_COLOR="\\033[38;5;${state.globalSepColor}m"`);
  }

  state.blocks.forEach(block => {
    if (!block.enabled) return;
    switch (block.id) {
      case 'model':
        lines.push(`MODEL_COLOR="\\033[38;5;${block.color}m"`);
        break;
      case 'context':
        lines.push(`CTX_LOW="\\033[38;5;${block.thresholds[0].color}m"`);
        lines.push(`CTX_MID="\\033[38;5;${block.thresholds[1].color}m"`);
        lines.push(`CTX_HIGH="\\033[38;5;${block.thresholds[2].color}m"`);
        if (block.showContextTokens) lines.push(`CTX_TOKENS_COLOR="\\033[38;5;${block.contextTokensColor ?? 243}m"`);
        break;
      case 'rate5h':
        lines.push(`RATE5H_COLOR="\\033[38;5;${block.color}m"`);
        if (block.showReset) lines.push(`RATE5H_RESET_COLOR="\\033[38;5;${block.colorReset ?? 238}m"`);
        break;
      case 'rateWeek':
        lines.push(`RATEWEEK_COLOR="\\033[38;5;${block.color}m"`);
        if (block.showReset) lines.push(`RATEWEEK_RESET_COLOR="\\033[38;5;${block.colorReset ?? 238}m"`);
        break;
      case 'tokens':
        lines.push(`TOKEN_COLOR="\\033[38;5;${block.color}m"`);
        break;
      case 'directory':
        lines.push(`DIR_COLOR="\\033[38;5;${block.color}m"`);
        if (block.showGit) {
          lines.push(`GIT_COLOR="\\033[38;5;${block.colorBranch}m"`);
        }
        break;
    }
  });

  lines.push('');

  // Bar function if rate blocks enabled
  if (hasRate) {
    const rateBlock = state.blocks.find(b => (b.id === 'rate5h' || b.id === 'rateWeek') && b.enabled);
    const style = rateBlock ? rateBlock.style : 'classic';
    if (style === 'emoji') {
      lines.push('get_rate_bar() {');
      lines.push('  local p=$1 len=${2:-8} bar=""');
      lines.push('  local filled=$(( p * len / 100 ))');
      lines.push('  local empty=$(( len - filled ))');
      lines.push('  local fc; if (( p < 50 )); then fc="🟢"; elif (( p < 80 )); then fc="🟡"; else fc="🔴"; fi');
      lines.push('  for ((i=0;i<filled;i++)); do bar+="$fc"; done');
      lines.push('  for ((i=0;i<empty;i++)); do bar+="⚪"; done');
      lines.push('  echo "$bar"');
      lines.push('}');
    } else if (style === 'gradient') {
      lines.push('get_rate_bar() {');
      lines.push('  local p=$1 len=${2:-8} bar=""');
      lines.push('  local filled=$(( p * len / 100 ))');
      lines.push('  local empty=$(( len - filled ))');
      lines.push('  for ((i=0;i<filled;i++)); do');
      lines.push('    local ratio=$(( i * 10 / len ))');
      lines.push('    if (( ratio < 4 )); then bar+="█"; elif (( ratio < 7 )); then bar+="▓"; else bar+="▒"; fi');
      lines.push('  done');
      lines.push('  for ((i=0;i<empty;i++)); do bar+="░"; done');
      lines.push('  echo "$bar"');
      lines.push('}');
    } else {
      const cfg = BAR_STYLES[style] || BAR_STYLES.classic;
      lines.push(`RATE_FILLED="${cfg.filled}"`);
      lines.push(`RATE_EMPTY="${cfg.empty}"`);
      lines.push('get_rate_bar() {');
      lines.push('  local p=$1 len=${2:-8} bar=""');
      lines.push('  local filled=$(( p * len / 100 ))');
      lines.push('  local empty=$(( len - filled ))');
      lines.push('  for ((i=0;i<filled;i++)); do bar+="${RATE_FILLED}"; done');
      lines.push('  for ((i=0;i<empty;i++)); do bar+="${RATE_EMPTY}"; done');
      lines.push('  echo "$bar"');
      lines.push('}');
    }
    lines.push('');
  }

  // Directory function
  const dirBlock = state.blocks.find(b => b.id === 'directory' && b.enabled);
  lines.push('get_directory() {');
  if (dirBlock && dirBlock.depth === 0) {
    lines.push('  echo "$1"');
  } else if (dirBlock && dirBlock.depth === 1) {
    lines.push('  echo "$(basename "$1")"');
  } else {
    lines.push('  local parent=$(basename "$(dirname "$1")")');
    lines.push('  local current=$(basename "$1")');
    lines.push('  if [[ "$parent" == "/" || -z "$parent" ]]; then echo "~/${current}"; else echo "~/${parent}/${current}"; fi');
  }
  lines.push('}');
  lines.push('');

  // Git helpers
  const gitBlock = state.blocks.find(b => b.id === 'git' && b.enabled);
  if (gitBlock) {
    lines.push('get_git_branch() { git -C "$1" rev-parse --abbrev-ref HEAD 2>/dev/null; }');
    lines.push('');
  }

  // Token format
  const tokBlock = state.blocks.find(b => b.id === 'tokens' && b.enabled);
  if (tokBlock) {
    if (tokBlock.format === '1000') {
      lines.push('format_tokens() { echo "$1"; }');
    } else if (tokBlock.format === '1.2k') {
      lines.push('format_tokens() { printf "%.1fk" "$(echo "scale=1; $1/1000" | bc)"; }');
    } else {
      lines.push('format_tokens() { echo "$(($1 / 1000))k"; }');
    }
    lines.push('');
  }

  // Context color
  const ctxBlock = state.blocks.find(b => b.id === 'context' && b.enabled);
  if (ctxBlock) {
    lines.push('get_ctx_color() {');
    lines.push('  local p=$1');
    lines.push(`  if (( p < ${ctxBlock.thresholds[0].max} )); then echo -e "$CTX_LOW"`);
    lines.push(`  elif (( p < ${ctxBlock.thresholds[1].max} )); then echo -e "$CTX_MID"`);
    lines.push('  else echo -e "$CTX_HIGH"');
    lines.push('  fi');
    lines.push('}');
    lines.push('');
  }

  // Compute values
  lines.push('# ── Compute values ──');
  lines.push('directory=$(get_directory "$cwd")');
  if (tokBlock) {
    lines.push('input_k=$(format_tokens "$input")');
    lines.push('output_k=$(format_tokens "$output")');
  }
  if (ctxBlock) {
    lines.push('ctx_color=$(get_ctx_color "$percent")');
  }
  lines.push('');

  // Print statusline
  lines.push('# ── Print statusline ──');
  let firstBlock = true;
  for (const block of state.blocks) {
    if (!block.enabled) continue;
    if (!firstBlock && state.globalSepEnabled && state.globalSep) {
      lines.push(`printf "\${SEP_COLOR}${state.globalSep}\${RESET} "`);
    }
    firstBlock = false;
    switch (block.id) {
      case 'model':
        lines.push(`printf "\${MODEL_COLOR}[%s]\${RESET}" "$model"`);
        break;
      case 'context':
        if (block.showContextTokens) {
          lines.push(`CTX_MAX=200000`);
          lines.push(`used_tokens=$((CTX_MAX * percent / 100 / 1000))`);
          lines.push(`max_tokens=$((CTX_MAX / 1000))`);
          lines.push(`printf "\${ctx_color}c%s%%\${RESET} \${CTX_TOKENS_COLOR}(%sK/%sK)\${RESET}" "$percent" "$used_tokens" "$max_tokens"`);
        } else {
          lines.push(`printf "\${ctx_color}c%s%%\${RESET}" "$percent"`);
        }
        break;
      case 'rate5h':
        lines.push('if [ -n "$five_h_left" ]; then');
        if (block.showBar) {
          lines.push(`  printf "\${RATE5H_COLOR}%s %s%%\${RESET}" "$(get_rate_bar $((100 - five_h_left)))" "$five_h_left"`);
        } else {
          lines.push(`  printf "\${RATE5H_COLOR}h%s%%\${RESET}" "$five_h_left"`);
        }
        if (block.showReset) {
          lines.push('  [ -n "$time_left" ] && printf " ${RATE5H_RESET_COLOR}%s${RESET}" "$time_left"');
        }
        lines.push('fi');
        break;
      case 'rateWeek':
        lines.push('if [ -n "$week_left" ]; then');
        if (block.showBar) {
          lines.push(`  printf "\${RATEWEEK_COLOR}%s %s%%\${RESET}" "$(get_rate_bar $((100 - week_left)))" "$week_left"`);
        } else {
          lines.push(`  printf "\${RATEWEEK_COLOR}w%s%%\${RESET}" "$week_left"`);
        }
        if (block.showReset) {
          lines.push('  [ -n "$week_reset_str" ] && printf " ${RATEWEEK_RESET_COLOR}%s${RESET}" "$week_reset_str"');
        }
        lines.push('fi');
        break;
      case 'tokens':
        lines.push(`printf "\${TOKEN_COLOR}↑%s ↓%s\${RESET}" "$input_k" "$output_k"`);
        break;
      case 'directory':
        lines.push(`printf "\${DIR_COLOR}%s\${RESET}" "$directory"`);
        if (block.showGit) {
          lines.push('if [[ -n "$cwd" ]]; then');
          lines.push('  git_branch=$(get_git_branch "$cwd")');
          lines.push('  if [[ -n "$git_branch" ]]; then');
          lines.push('    printf " \${GIT_COLOR}(%s)\${RESET}" "$git_branch"');

          lines.push('  fi');
          lines.push('fi');
        }
        break;
    }
    lines.push(`printf " "`);
  }

  lines.push('');
  return lines.join('\n');
}
